services:
  database:
    container_name: postgres_independent_project
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: TempXXL2024
      POSTGRES_HOST_AUTH_METHOD:
    ports:
      - "5434:5432"